# Generated by Django 4.0.4 on 2022-07-23 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='avatar_file',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='password_strength',
        ),
    ]
