# Generated by Django 4.0.4 on 2022-08-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='note',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
