# Generated by Django 4.0.4 on 2022-08-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_remove_listitem_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
